image: atlassian/default-image:2
pipelines:
  default:
  - step:
      deployment: production
      script:
      - git submodule update --recursive --init
      - zip -r $FILENAME . -x bitbucket-pipelines.yml *.git*
      - pipe: atlassian/bitbucket-upload-file:0.1.6
        variables:
          BITBUCKET_USERNAME: $BITBUCKET_USERNAME
          BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
          FILENAME: $FILENAME
